#!/bin/bash

echo "Downloading the latest BedrockConnect release"
cd /BedrockConnect
curl -L https://github.com/Pugmatt/BedrockConnect/releases/latest/download/BedrockConnect-1.0-SNAPSHOT.jar --output bedrock_connect.jar
